checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-jammy

  nodes:
    analysis:
      environment:
        php: 8.2
      project_setup:
        override:
          - "true"
      tests:
        override:
          - php-scrutinizer-run
